# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  north_wm_config = debug

else ifeq ($(config),release)
  north_wm_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := north_wm

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

north_wm:
ifneq (,$(north_wm_config))
	@echo "==== Building north_wm ($(north_wm_config)) ===="
	@${MAKE} --no-print-directory -C . -f north_wm.make config=$(north_wm_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f north_wm.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   north_wm"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"