# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=core
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),core)
  wm_config = core

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := wm

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

wm:
ifneq (,$(wm_config))
	@echo "==== Building wm ($(wm_config)) ===="
	@${MAKE} --no-print-directory -C . -f wm.make config=$(wm_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f wm.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  core"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   wm"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"